import type { Metadata } from "next";
import ServicePage from "../components/ServicePage";
export const metadata: Metadata = { title: "Privacy Policy" };
export default function PrivacyPage() {
  return <ServicePage title="Privacy Policy" intro="This notice explains how information is handled through Hometown Perks websites, inquiries, and the merchant portal.">
    <p>Effective October 7, 2026. These services are operated by Hometown Perks, LLC. This notice applies to Hometown Perks services, not to Kentucky Belle Boutique’s separate website or operations.</p>
    <section><h2 className="text-2xl font-semibold text-white">Information you provide</h2><p className="mt-3">An inquiry includes your business name, contact name, email, optional phone number, service area, optional message, service interests, and permission to follow up. The merchant portal stores account and business details, ad requests and files, Connect Plate settings and links, and documents attached to your merchant account. Please do not include full card numbers, passwords, Social Security numbers, or unrelated sensitive information in messages or uploaded files.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">How information is used</h2><p className="mt-3">Information supports responses to inquiries, account access, requested services, ad review, merchant documents, billing records when applicable, and troubleshooting and protection against misuse. Submitting interest records your inquiry and consent to contact you; it does not create a paid subscription.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Public content and private records</h2><p className="mt-3">Connect Plate business pages can display the business information, promotional content, and links you submit. Approved advertising is intended for public display. Keep private information out of these materials. Uploaded merchant agreements are stored separately from public pages, with access restricted to authorized owner access and the linked merchant account. PDF access uses temporary links; anyone you share an opened file or link with may be able to access that copy.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Service providers and external services</h2><p className="mt-3">Vercel supports website hosting; Supabase supports portal authentication, database records, and file storage. Square supports payment services when used, and Zoho supports business email. These providers process information needed for their roles. Community gift-card services and external links may take you to Yiftee or other providers whose own notices and terms apply. Full payment-card details should be entered only into the payment provider’s secure payment interface.</p><p className="mt-3">Records may also be disclosed when required by law or reasonably necessary to address fraud, security incidents, or protect rights. This notice does not authorize publishing private agreements as advertisements.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Browser storage and activity</h2><p className="mt-3">The portal uses browser storage to maintain your sign-in session. Hosting and authentication services may process technical information such as IP addresses, device or browser information, request times, and error logs. Connect Plate pages record page visits and link-click events for merchant activity counts. Disabling browser storage may prevent portal features from working. Sign out when using a shared device.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Requests and retention</h2><p className="mt-3">Contact us to ask about your information, request a correction or deletion, or stop inquiry follow-up. We may need to verify your identity and retain information needed for active services, agreements, billing, dispute resolution, security, or legal obligations. Deletion may affect portal access or available records, and provider backups may retain copies according to their own processes. No online system can guarantee complete security.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Contact and updates</h2><p className="mt-3">Send privacy requests to <a className="break-all underline" href="mailto:info@hometownperksusa.com">info@hometownperksusa.com</a>. Do not email your password or full card details. Updates will be posted here with a revised effective date.</p></section>
  </ServicePage>;
}
