import type { Metadata } from "next";
import ServicePage from "../components/ServicePage";
export const metadata: Metadata = { title: "Website Terms" };
export default function TermsPage() {
  return <ServicePage title="Website Terms" intro="These terms explain use of the Hometown Perks website and merchant portal. Service purchases require their own applicable agreement and authorization.">
    <p>Effective October 7, 2026. The website and portal are operated by Hometown Perks, LLC. Kentucky Belle Boutique is a separate business; these terms do not govern its sales or website.</p>
    <section><h2 className="text-2xl font-semibold text-white">Inquiries and availability</h2><p className="mt-3">An interest-form submission requests information and follow-up. It does not create an account, reserve screen inventory, start advertising, authorize a charge, or establish a subscription. Paid advertising enrollment is currently closed. Planned services, example dashboards, and prospective locations are not confirmation that a campaign or location is active. Campaign availability and participating locations will be confirmed before service begins.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Advertising and future payments</h2><p className="mt-3">The planned advertising package is $149 paid upfront for the first 30 calendar days. That period begins when your approved ad goes live. Subsequent $149 monthly renewals require separate authorization. Authorized monthly service is month-to-month; cancel before the next charge to stop future renewal, with access continuing through the paid period. Any optional Connect Plate pricing and service details must be confirmed separately. A page visit, inquiry, ad submission, or document upload does not itself authorize payment or renewal. The applicable signed service agreement and payment authorization provide the purchase-specific terms, including any refund terms.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Accounts and acceptable use</h2><p className="mt-3">Provide accurate information and use only accounts and business records you are authorized to manage. Protect your credentials, sign out on shared devices, and notify us of suspected unauthorized access. Do not attempt to access another merchant’s private information, upload malicious files, interfere with the service, or submit unlawful or misleading content.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Submitted content and documents</h2><p className="mt-3">Submit only material you have permission to use, including images, logos, advertising claims, and links. By submitting content for a requested service, you permit Hometown Perks and its supporting providers to store and process it to deliver that service, and to display material intended for public promotion. Ad requests require review and approval before a campaign goes live. Merchant agreements are private account documents; attaching a PDF does not sign it, certify its contents, or activate advertising or billing.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">External providers and service changes</h2><p className="mt-3">Third-party gift cards, payment services, and linked websites have their own terms and policies. Review the provider’s terms before making a purchase. Website features may be updated or temporarily unavailable for maintenance or technical issues. Advertising does not guarantee impressions, customer visits, or sales unless a specific written agreement expressly provides a measurable commitment.</p></section>
    <section><h2 className="text-2xl font-semibold text-white">Privacy, help, and updates</h2><p className="mt-3">See our <a className="underline" href="/privacy">Privacy Policy</a> for information handling. Questions about the website, an account, or these terms may be sent to <a className="break-all underline" href="mailto:info@hometownperksusa.com">info@hometownperksusa.com</a>. Billing and service inquiries may be sent to <a className="break-all underline" href="mailto:michael@hometownperksusa.com">michael@hometownperksusa.com</a>. Updates will be posted here with a revised effective date. Changes to this page alone do not supply payment authorization.</p></section>
  </ServicePage>;
}
